project:
  type: book

book:
  title: "stata-textbook"
  authors: "Norah Jones"
  date: "10/12/2025"
  chapters:
    - index.qmd
    - chapters/chapter1_data.qmd
    - chapters/chapter2_regression.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



